import { defineTrivia, type TriviaFact } from "@hasystor/content-schema";

const facts: TriviaFact[] = defineTrivia([
  {
    id: "cpython-list-growth",
    prompt: "How does CPython grow a list's backing array on append?",
    answer: "new_allocated = n + (n >> 3) + (n < 9 ? 3 : 6), then rounded up.",
    explanation: "Geometric-ish overallocation (~1.125x + a constant) gives amortized O(1) append.",
    tags: ["python", "amortized", "data-structures"],
    difficulty: "medium",
    sourceRef: "CPython listobject.c list_resize",
  },
  {
    id: "page-size-4k",
    prompt: "What is the typical x86-64 page size, and how many offset bits does it imply?",
    answer: "4 KiB; 12 offset bits.",
    explanation: "2^12 = 4096. Huge pages are 2 MiB or 1 GiB.",
    tags: ["virtual-memory", "paging"],
    difficulty: "easy",
    sourceRef: "CS:APP ch.9",
  },
  {
    id: "cache-line-64",
    prompt: "What is the typical CPU cache line size on x86-64?",
    answer: "64 bytes.",
    explanation: "Memory moves between cache levels in 64-byte lines; it drives locality and false sharing.",
    tags: ["cache", "performance"],
    difficulty: "easy",
  },
  {
    id: "false-sharing",
    prompt: "What is false sharing?",
    answer: "Two threads writing different variables that share one cache line, causing coherence ping-pong.",
    explanation: "Fix by padding/aligning hot per-thread data to separate cache lines.",
    tags: ["cache", "concurrency", "false-sharing"],
    difficulty: "medium",
  },
  {
    id: "twos-complement",
    prompt: "How do you negate a two's-complement integer?",
    answer: "Invert all bits and add one: -x == ~x + 1.",
    explanation: "This is why subtraction reuses the adder and why INT_MIN has no positive counterpart.",
    tags: ["representation", "twos-complement", "c"],
    difficulty: "easy",
  },
  {
    id: "signed-overflow-ub",
    prompt: "What happens on signed integer overflow in C?",
    answer: "It is undefined behavior; unsigned overflow wraps modulo 2^N.",
    explanation: "Compilers may assume signed overflow never happens when optimizing.",
    tags: ["c", "ub", "overflow"],
    difficulty: "medium",
  },
  {
    id: "endianness",
    prompt: "What byte order does x86 use, and what is 'network byte order'?",
    answer: "x86 is little-endian; network byte order is big-endian.",
    explanation: "Use htonl/ntohl to convert between host and network order.",
    tags: ["representation", "endianness", "networking"],
    difficulty: "easy",
  },
  {
    id: "ieee754-nan",
    prompt: "How is NaN encoded in IEEE-754, and what is special about comparing it?",
    answer: "Exponent all ones with a nonzero mantissa; NaN != NaN is true.",
    explanation: "Always use isnan(); equality comparisons against NaN are always false.",
    tags: ["ieee754", "representation"],
    difficulty: "medium",
  },
  {
    id: "malloc-alignment",
    prompt: "What alignment does malloc guarantee on 64-bit systems?",
    answer: "At least 16-byte alignment (max_align_t).",
    explanation: "So returned memory is suitable for any built-in type, including SIMD-ish 16-byte types.",
    tags: ["memory", "allocator"],
    difficulty: "medium",
  },
  {
    id: "stack-grows-down",
    prompt: "Which direction does the call stack grow on x86-64?",
    answer: "Down, toward lower addresses.",
    explanation: "push decrements rsp; the heap conventionally grows up.",
    tags: ["memory", "x86-64-abi"],
    difficulty: "easy",
  },
  {
    id: "tlb",
    prompt: "What does the TLB cache?",
    answer: "Recent virtual-to-physical address translations.",
    explanation: "A TLB miss triggers a page-table walk, which is far slower.",
    tags: ["virtual-memory", "tlb", "cache"],
    difficulty: "easy",
  },
  {
    id: "cow-fork",
    prompt: "How does fork() share memory with the child efficiently?",
    answer: "Copy-on-write: pages are shared read-only until one side writes.",
    explanation: "The first write faults and copies just that page.",
    tags: ["processes", "virtual-memory"],
    difficulty: "medium",
  },
  {
    id: "async-signal-safe",
    prompt: "Why can't you call printf() inside a signal handler?",
    answer: "printf isn't async-signal-safe; only a small set (e.g., write) is.",
    explanation: "A signal can interrupt the same function mid-update, corrupting state.",
    tags: ["signals", "processes"],
    difficulty: "medium",
  },
  {
    id: "eintr",
    prompt: "What is EINTR and how do you handle it?",
    answer: "A slow syscall was interrupted by a signal; retry the call (or use SA_RESTART).",
    explanation: "Robust I/O loops check for EINTR and retry.",
    tags: ["signals", "processes"],
    difficulty: "medium",
  },
  {
    id: "zombie-process",
    prompt: "What is a zombie process?",
    answer: "A terminated child whose exit status hasn't been reaped by wait().",
    explanation: "Always wait()/waitpid() on children to release their PCB entry.",
    tags: ["processes"],
    difficulty: "easy",
  },
  {
    id: "deadlock-conditions",
    prompt: "What are the four necessary conditions for deadlock?",
    answer: "Mutual exclusion, hold-and-wait, no preemption, and circular wait.",
    explanation: "Break any one (e.g., global lock ordering removes circular wait) to prevent deadlock.",
    tags: ["concurrency", "deadlock"],
    difficulty: "medium",
  },
  {
    id: "aba-problem",
    prompt: "What is the ABA problem in lock-free programming?",
    answer: "A value reads as A, changes to B, then back to A, fooling a CAS into seeing 'no change'.",
    explanation: "Mitigate with tagged pointers, hazard pointers, or epoch-based reclamation.",
    tags: ["concurrency", "lockfree", "aba-problem"],
    difficulty: "hard",
  },
  {
    id: "memory-ordering",
    prompt: "What do acquire and release memory orderings do?",
    answer: "Release publishes prior writes; a matching acquire observes them — cheaper than seq_cst.",
    explanation: "They create a happens-before edge between a releasing store and an acquiring load.",
    tags: ["concurrency", "memory-ordering"],
    difficulty: "hard",
  },
  {
    id: "mutex-vs-spinlock",
    prompt: "When should you prefer a spinlock over a mutex?",
    answer: "When critical sections are tiny and contention is low, so spinning is cheaper than blocking.",
    explanation: "Spinning wastes CPU under contention; mutexes block and let the scheduler run others.",
    tags: ["concurrency"],
    difficulty: "medium",
  },
  {
    id: "volatile-not-atomic",
    prompt: "Does C 'volatile' make a variable thread-safe?",
    answer: "No. volatile prevents some optimizations but provides no atomicity or ordering.",
    explanation: "Use atomics (stdatomic.h) for inter-thread synchronization.",
    tags: ["concurrency", "c"],
    difficulty: "medium",
  },
  {
    id: "rr-quantum",
    prompt: "What trade-off does the round-robin time quantum control?",
    answer: "Small quantum = better responsiveness but more context-switch overhead.",
    explanation: "Too small thrashes on switches; too large degrades toward FIFO.",
    tags: ["scheduling"],
    difficulty: "easy",
  },
  {
    id: "convoy-effect",
    prompt: "What is the convoy effect?",
    answer: "Short jobs stuck waiting behind one long job under FIFO scheduling.",
    explanation: "SJF/RR reduce it by not letting one long job monopolize the CPU.",
    tags: ["scheduling"],
    difficulty: "medium",
  },
  {
    id: "inode",
    prompt: "What does an inode store?",
    answer: "File metadata and block pointers — but not the file's name.",
    explanation: "Names live in directory entries that map to inode numbers.",
    tags: ["fs"],
    difficulty: "easy",
  },
  {
    id: "fsync",
    prompt: "What does fsync() guarantee?",
    answer: "That a file's data is flushed to durable storage (metadata too, if you fsync the dir).",
    explanation: "Critical for crash consistency in databases and logs.",
    tags: ["fs", "durability"],
    difficulty: "medium",
  },
  {
    id: "write-amplification",
    prompt: "What is write amplification?",
    answer: "When one logical write causes multiple physical writes.",
    explanation: "Common in SSDs (erase blocks) and LSM-trees (compaction).",
    tags: ["storage"],
    difficulty: "medium",
  },
  {
    id: "tcp-handshake",
    prompt: "What are the steps of the TCP connection handshake?",
    answer: "SYN, SYN-ACK, ACK (three-way).",
    explanation: "Teardown is a four-way FIN/ACK exchange plus TIME_WAIT.",
    tags: ["networking"],
    difficulty: "easy",
  },
  {
    id: "nagle",
    prompt: "What does Nagle's algorithm do, and how do you disable it?",
    answer: "It coalesces small TCP writes to reduce tiny packets; disable with TCP_NODELAY.",
    explanation: "Disabling helps latency-sensitive workloads at the cost of more packets.",
    tags: ["networking"],
    difficulty: "medium",
  },
  {
    id: "epoll-vs-select",
    prompt: "Why does epoll scale better than select for many connections?",
    answer: "epoll reports readiness in roughly O(1); select scans all fds at O(n) each call.",
    explanation: "epoll maintains kernel-side interest lists, key to handling C10k.",
    tags: ["networking"],
    difficulty: "medium",
  },
  {
    id: "btree-fanout",
    prompt: "Why do databases favor B-trees for on-disk indexes?",
    answer: "High fanout keeps the tree shallow, minimizing slow page/disk accesses.",
    explanation: "Each node holds many keys, so few levels are needed for huge datasets.",
    tags: ["storage", "databases"],
    difficulty: "medium",
  },
  {
    id: "lsm-compaction",
    prompt: "How does an LSM-tree handle writes?",
    answer: "Buffer in an in-memory memtable, flush sorted runs, then compact them in the background.",
    explanation: "Write-optimized; reads may check multiple runs plus a bloom filter.",
    tags: ["storage", "databases"],
    difficulty: "hard",
  },
  {
    id: "clock-algo",
    prompt: "What is the CLOCK page-replacement algorithm?",
    answer: "An LRU approximation using a reference bit and a rotating hand.",
    explanation: "Cheaper than true LRU; evicts the first page whose reference bit is 0.",
    tags: ["caching", "virtual-memory"],
    difficulty: "medium",
  },
  {
    id: "mvcc",
    prompt: "What does MVCC give a database?",
    answer: "Readers see a consistent snapshot without blocking writers (and vice versa).",
    explanation: "Multiple versions of a row coexist; visibility depends on transaction timestamps.",
    tags: ["databases"],
    difficulty: "hard",
  },
  {
    id: "static-vs-dynamic-link",
    prompt: "What is the difference between static and dynamic linking?",
    answer: "Static (.a) bakes code into the binary; dynamic (.so) loads shared libraries at runtime.",
    explanation: "Dynamic linking saves space and allows updates but adds load-time resolution (PLT/GOT).",
    tags: ["toolchain"],
    difficulty: "easy",
  },
  {
    id: "sanitizers",
    prompt: "What do ASan, TSan, and UBSan detect?",
    answer: "Memory errors, data races, and undefined behavior — respectively — at runtime.",
    explanation: "HastOS grades concurrency problems under TSan and memory problems under ASan.",
    tags: ["tools", "testing"],
    difficulty: "medium",
  },
  {
    id: "latency-numbers",
    prompt: "Order these by latency: L1 cache, DRAM, SSD, cross-datacenter network.",
    answer: "L1 (~1ns) < DRAM (~100ns) < SSD (~100us) < cross-DC network (~ms).",
    explanation: "Each step is roughly 100-1000x slower; this cost model guides optimization.",
    tags: ["performance"],
    difficulty: "medium",
  },
]);

export default facts;
