import { defineTrivia, type TriviaFact } from "@hasystor/content-schema";

const facts: TriviaFact[] = defineTrivia([
  {
    id: "twos-complement-min",
    prompt: "Why is -INT_MIN undefined behavior for a 32-bit signed int?",
    answer: "INT_MIN is -2147483648; its negation 2147483648 overflows INT_MAX (2147483647).",
    explanation: "Two's complement is asymmetric — one more negative value than positive — so negating INT_MIN overflows.",
    tags: ["integers", "undefined-behavior"],
    difficulty: "medium",
  },
  {
    id: "memcpy-vs-memmove",
    prompt: "When must you use memmove instead of memcpy?",
    answer: "When the source and destination regions overlap.",
    explanation: "memcpy is UB on overlap; memmove copies in a safe direction (or via a temp) to handle it.",
    tags: ["c", "memory", "memcpy-memmove"],
    difficulty: "easy",
  },
  {
    id: "clear-lowest-bit",
    prompt: "What does the expression x & (x - 1) compute?",
    answer: "x with its lowest set bit cleared.",
    explanation: "Subtracting 1 flips the lowest set bit and all zeros below it; ANDing clears that bit. If the result is 0 (and x != 0), x is a power of two.",
    tags: ["bit-tricks"],
    difficulty: "easy",
  },
  {
    id: "isolate-lowest-bit",
    prompt: "What does x & (-x) give for a nonzero integer x?",
    answer: "A mask with only the lowest set bit of x.",
    explanation: "-x is ~x + 1 (two's complement), which shares only the lowest set bit with x. Used in Fenwick/BIT trees.",
    tags: ["bit-tricks"],
    difficulty: "medium",
  },
  {
    id: "vector-growth-factor",
    prompt: "Why do some dynamic arrays grow by ~1.5x instead of 2x?",
    answer: "A factor below 2 lets freed blocks be reused by later allocations (better memory reuse).",
    explanation: "With 2x, the new block is always larger than the sum of all previous blocks, so it can never reuse them; ~1.5x eventually can.",
    tags: ["amortized", "data-structures"],
    difficulty: "hard",
  },
  {
    id: "syscall-cost",
    prompt: "Roughly how expensive is a system call versus a plain function call?",
    answer: "Hundreds of cycles (mode switch + register save/restore) vs. a few cycles.",
    explanation: "This is why high-throughput I/O batches work (big buffers, epoll, io_uring) to amortize the crossing.",
    tags: ["os", "ecf", "performance"],
    difficulty: "medium",
  },
  {
    id: "fork-cow",
    prompt: "Why is fork() fast despite giving the child a full copy of memory?",
    answer: "Copy-on-write: pages are shared read-only and only duplicated on the first write.",
    explanation: "fork mostly just copies page tables; fork+exec barely copies anything before the image is replaced.",
    tags: ["os", "processes", "virtual-memory"],
    difficulty: "medium",
  },
  {
    id: "tlb-reach",
    prompt: "What is 'TLB reach' and how do huge pages improve it?",
    answer: "Reach = entries x page size; a 2 MiB huge page maps 512x more per entry than a 4 KiB page.",
    explanation: "Big working sets thrash a 4 KiB TLB; huge pages cover far more memory with the same entry count.",
    tags: ["virtual-memory", "paging", "performance"],
    difficulty: "hard",
  },
  {
    id: "false-sharing-fix",
    prompt: "Two threads update separate counters but throughput collapses. Likely cause and fix?",
    answer: "False sharing — the counters share a cache line; pad/align each to its own 64-byte line.",
    explanation: "Coherence is line-granular, so writes to one variable invalidate the other core's copy of the whole line.",
    tags: ["concurrency", "cache", "performance"],
    difficulty: "medium",
  },
  {
    id: "aba-problem",
    prompt: "What is the ABA problem in lock-free code?",
    answer: "A value reads A, changes to B, then back to A, so a CAS wrongly succeeds as if nothing changed.",
    explanation: "Fix with tagged/versioned pointers, hazard pointers, or epoch/RCU reclamation.",
    tags: ["concurrency", "lock-free"],
    difficulty: "hard",
  },
  {
    id: "acquire-release",
    prompt: "What ordering pair implements the 'publish then consume' pattern cheaply?",
    answer: "A release store paired with an acquire load.",
    explanation: "Writes before the release become visible to a thread after the matching acquire — a happens-before edge; it's what unlock/lock map to.",
    tags: ["concurrency", "memory-model"],
    difficulty: "hard",
  },
  {
    id: "x86-tso",
    prompt: "Which single reordering does x86-64 (TSO) still allow?",
    answer: "StoreLoad — a later load can bypass an earlier store to a different address (store buffer).",
    explanation: "This is why seq_cst needs a full barrier (mfence/lock) on x86 while acquire/release are nearly free.",
    tags: ["concurrency", "memory-model"],
    difficulty: "hard",
  },
  {
    id: "belady-anomaly",
    prompt: "What is Belady's anomaly?",
    answer: "For FIFO page replacement, adding more frames can increase the number of misses.",
    explanation: "Stack algorithms like LRU/OPT don't suffer it because a larger cache is a superset of a smaller one.",
    tags: ["os", "caching"],
    difficulty: "hard",
  },
  {
    id: "wal-rule",
    prompt: "What is the write-ahead logging (WAL) rule?",
    answer: "Write the intended change (and its commit) to the log before applying it in place.",
    explanation: "On crash, replay committed transactions and discard uncommitted ones — recovery is proportional to the log, not disk size.",
    tags: ["storage", "databases", "crash-consistency"],
    difficulty: "medium",
  },
  {
    id: "btree-vs-lsm",
    prompt: "B-tree vs. LSM-tree: which is read-optimized and which is write-optimized?",
    answer: "B-tree is read-optimized (in-place, sorted); LSM is write-optimized (buffer + sequential flush + compaction).",
    explanation: "Write-heavy workloads favor LSM; read/scan-heavy favor B-trees. It's a point on the RUM (read/update/memory) triangle.",
    tags: ["storage", "databases"],
    difficulty: "medium",
  },
  {
    id: "tcp-no-framing",
    prompt: "Why must an app protocol over TCP add its own message framing?",
    answer: "TCP is a byte stream with no message boundaries — reads can split or merge sends.",
    explanation: "Use a length prefix or a delimiter; assuming one write == one read is a classic bug.",
    tags: ["networking", "tcp"],
    difficulty: "medium",
  },
  {
    id: "epoll-scaling",
    prompt: "Why does epoll scale better than select for many connections?",
    answer: "select rescans all fds each call (O(n)); epoll registers interest once and returns only ready fds (~O(1)).",
    explanation: "This is what made solving the C10k problem practical for event-driven servers.",
    tags: ["networking", "os", "performance"],
    difficulty: "medium",
  },
  {
    id: "p99-latency",
    prompt: "Why track p99 latency instead of the average?",
    answer: "Averages hide the tail; the slowest ~1% often dominate user-perceived pain and reveal contention/GC/queueing.",
    explanation: "A good average can mask a terrible p99; measure percentiles for latency-sensitive systems.",
    tags: ["performance", "observability"],
    difficulty: "medium",
  },
  {
    id: "stack-grows-down",
    prompt: "Which direction does the stack grow on x86-64, and what instruction moves the stack pointer on a push?",
    answer: "Downward (toward lower addresses); push decrements rsp by 8 then stores.",
    explanation: "The return address on the stack is exactly what stack buffer overflows target.",
    tags: ["machine", "stack", "security"],
    difficulty: "easy",
  },
  {
    id: "lea-no-memory",
    prompt: "What does the x86 lea instruction do that mov does not?",
    answer: "It computes an address (base + index*scale + disp) without accessing memory.",
    explanation: "Compilers love lea as a fast multiply-and-add that also leaves the flags untouched.",
    tags: ["machine", "assembly"],
    difficulty: "medium",
  },
]);

export default facts;
